dist: xenial

language: python

python:
  - "3.7"

services:
  - postgresql

before_install:
  - pip install pipenv

install:
  - cp .travis.env .env
  - pipenv sync --dev

before_script:
  - psql -U postgres -c 'CREATE DATABASE receipts;'

script:
  - pytest --cov
