version: '3.4'

services:

  db:
    image: postgres:alpine
    env_file:
      - .env

  tests:
    build:
      context: .
      target: dev
    image: receipt-tracker:dev
    volumes:
      - ./receipt_tracker:/opt/receipt-tracker/receipt_tracker
    env_file:
      - .env
    depends_on:
      - db
