version: '3.4'

services:

  db:
    image: postgres:alpine
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env

  message-broker:
    image: rabbitmq:alpine
    volumes:
      - messages:/var/lib/rabbitmq

  backend:
    build:
      context: .
      target: prod
    image: receipt-tracker
    volumes:
      - static:/opt/static
      - ./conf/gunicorn.conf:/etc/gunicorn.conf
      - ./receipt_tracker:/opt/receipt-tracker/receipt_tracker
    env_file:
      - .env
    depends_on:
      - db
      - message-queue

  message-queue:
    build:
      context: .
      target: prod
    image: receipt-tracker
    volumes:
      - ./receipt_tracker:/opt/receipt-tracker/receipt_tracker
    command: ["celery", "-A", "receipt_tracker.celery", "worker"]
    env_file:
      - .env
    depends_on:
      - db
      - message-broker

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - static:/opt/s
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  db:
  messages:
  static:
