# Generated by Django 2.1.7 on 2019-03-30 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddReceiptTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_drive_number', models.BigIntegerField()),
                ('fiscal_document_number', models.BigIntegerField()),
                ('fiscal_sign', models.BigIntegerField()),
                ('total_sum', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Новое'), (1, 'Выполнено'), (2, 'Не выполнено')], default=0)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.PositiveIntegerField(help_text='На сто грамм')),
                ('protein', models.DecimalField(decimal_places=2, help_text='На сто грамм', max_digits=4)),
                ('fat', models.DecimalField(decimal_places=2, help_text='На сто грамм', max_digits=4)),
                ('carbohydrate', models.DecimalField(decimal_places=2, help_text='На сто грамм', max_digits=4)),
                ('weight', models.PositiveSmallIntegerField(help_text='В граммах')),
            ],
        ),
        migrations.CreateModel(
            name='NonFoodProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_friendly_name', models.CharField(blank=True, max_length=100, null=True)),
                ('barcode', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipt_tracker.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('fiscal_drive_number', models.BigIntegerField()),
                ('fiscal_document_number', models.BigIntegerField()),
                ('fiscal_sign', models.BigIntegerField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=6)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_alias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipt_tracker.ProductAlias')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipt_tracker.Receipt')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual_number', models.PositiveIntegerField(unique=True)),
                ('original_name', models.CharField(max_length=100)),
                ('user_friendly_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='receipt',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipt_tracker.Seller'),
        ),
        migrations.AddField(
            model_name='productalias',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipt_tracker.Seller'),
        ),
        migrations.AddField(
            model_name='nonfoodproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='receipt_tracker.Product'),
        ),
        migrations.AddField(
            model_name='foodproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='receipt_tracker.Product'),
        ),
        migrations.AlterUniqueTogether(
            name='receipt',
            unique_together={('fiscal_drive_number', 'fiscal_document_number', 'fiscal_sign')},
        ),
        migrations.AlterUniqueTogether(
            name='addreceipttask',
            unique_together={('fiscal_drive_number', 'fiscal_document_number', 'fiscal_sign')},
        ),
    ]
