# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='short_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
