# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='receiptitem',
            unique_together=set([]),
        ),
    ]
