# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 07:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_seller_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddReceiptTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_drive_number', models.BigIntegerField()),
                ('fiscal_document_number', models.BigIntegerField()),
                ('fiscal_sign', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Новое'), (1, 'Выполнено'), (2, 'Не выполнено')], default=0)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='addreceipttask',
            unique_together=set([('fiscal_drive_number', 'fiscal_document_number', 'fiscal_sign')]),
        ),
    ]
