# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 04:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170618_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
