# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170628_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='addreceipttask',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
