# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_addreceipttask_total_sum'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.PositiveIntegerField(help_text='На сто грамм')),
                ('protein', models.DecimalField(decimal_places=2, help_text='На сто грамм', max_digits=4)),
                ('fat', models.DecimalField(decimal_places=2, help_text='На сто грамм', max_digits=4)),
                ('carbohydrate', models.DecimalField(decimal_places=2, help_text='На сто грамм', max_digits=4)),
                ('weight', models.PositiveSmallIntegerField(help_text='В граммах')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Product'),
        ),
    ]
