# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170705_0347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='user_friendly_name',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='name',
            new_name='original_name',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='short_name',
            new_name='user_friendly_name',
        ),
    ]
