# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170707_0316'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonFoodProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Product')),
            ],
        ),
    ]
